version: '0.1'
services:  

  front:
    container_name: nextjs_front
    image: nextjs-front:1.0.0
    build: client/
    command: npm run start
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    depends_on:
      - back
    restart: unless-stopped


  back:
    container_name: nestjs_api
    image: nestjs-api:1.0.0
    build: server/
    command: npm run start:debug
    ports:
      - 5000:5000
    networks:
      - nesjs-network
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_HOST: 'mongodock'
    restart: unless-stopped  
  
  
  mongodb:
    image : mongo:latest
    container_name: mongodock
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always  
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  

networks:
  nesjs-network:
    driver: bridge
